default: &default
  20000: &20000
    trans_history_search_range: [30, 'search range of transaction history(day)']
    polling_time: [1, 'interval of refreshing header(minute)']
    card_id_length: [20]
    member_id_length: [8]
    audit_log_search_range: [7, 'search range of audit log(day)']
    change_log_search_range: [30, 'search range of player lock log(day)']
    pin_log_search_range: [30, 'search range of pin log(day)']
    account_activity_search_range: [24, 'search range of account_activity(hour)']
    token_life_time: [30]
    transaction_void_range: [1, 'void range of transaction(day)']
    session_life_time: [60]
    roll_shift_time: ['6,14,22', 'utc time of rolling shift(hour)']
    credit_life_time_array: ['0.5,1,3,5,7', 'array of credit life time options (day)']
    daily_deposit_limit: [25000000, 'limit amount of daily deposit (cent)']
    daily_withdraw_limit: [25000000, 'limit amount of daily withdraw (cent)']
    deposit_authorized_amount: [5000000, 'authorized amount of deposit (cent)']
    withdraw_authorized_amount: [5000000, 'authorized amount of withdraw (cent)']
    void_deposit_authorized_amount: [5000000, 'authorized amount of void deposit (cent)']
    void_withdraw_authorized_amount: [5000000, 'authorized amount of void deposit (cent)']
    deposit_transaction_limit: [5000000, 'limit amount of deposit transaction (cent)']
    withdraw_transaction_limit: [5000000, 'limit amount of withdraw transaction (cent)']

 #   source_of_funds: ['Business earnings,Salary or wages,Savings,Winnings,Marker,Other(Please specify manually in remark)','type of funds']
  #  payment_method_types: ['Credit Cards,Debit Cards,Cashier Order,Casino Cheque,Personal Cheque,TT-in,Cash Chips,Marker','types payment method']
  40000:
    <<: *20000
  20001:
    <<: *20000
  20002:
    <<: *20000
  10000:
    <<: *20000
  10001:
    <<: *20000
  12000:
    <<: *20000
    session_life_time: [30]
  10006:
    <<: *20000
    session_life_time: [30]
  10010:
    <<: *20000
    trans_history_search_range: [40, 'search range of transaction history(day)']
    change_log_search_range: [40, 'search range of player lock log(day)']
    pin_log_search_range: [40, 'search range of pin log(day)']
    session_life_time: [10]
    roll_shift_time: ['22', 'utc time of rolling shift(hour)']

development:
  <<: *default

test:
  20000:
    trans_history_search_range: [30, 'search range of transaction history(day)']
    polling_time: [1, 'interval of refreshing header(minute)']
    card_id_length: [20]
    member_id_length: [8]
    audit_log_search_range: [7, 'search range of audit log(day)']
    change_log_search_range: [30, 'search range of player lock log(day)']
    pin_log_search_range: [30, 'search range of pin log(day)']
    account_activity_search_range: [24, 'search range of account_activity(hour)']
    token_life_time: [30]
    transaction_void_range: [1, 'void range of transaction(day)']
    session_life_time: [60]
    roll_shift_time: ['6,14,22', 'utc time of rolling shift(hour)']
    credit_life_time_array: ['0.5,1,3,5,7', 'array of credit life time options (day)']
    daily_deposit_limit: [20000, 'limit amount of daily deposit (cent)']
    daily_withdraw_limit: [20000, 'limit amount of daily withdraw (cent)']
    deposit_authorized_amount: [5000000]
    withdraw_authorized_amount: [5000000]
    void_deposit_authorized_amount: [5000000]
    void_withdraw_authorized_amount: [5000000]
  10010:
    daily_deposit_limit: [20000, 'limit amount of daily deposit (cent)']
    daily_withdraw_limit: [20000, 'limit amount of daily withdraw (cent)']

mockup0:
  <<: *default

integration0:
  <<: *default

staging0:
  <<: *default

staging1:
  <<: *default

sandbox5:
  <<: *default

sandbox3:
  <<: *default

production3:
  <<: *default

ias_prd:
  <<: *default

sandbox:
  9000:
    trans_history_search_range: [30, 'search range of transaction history(day)']
    polling_time: [1, 'interval of refreshing header(minute)']
    card_id_length: [20]
    member_id_length: [8]
    audit_log_search_range: [7, 'search range of audit log(day)']
    change_log_search_range: [30, 'search range of player lock log(day)']
    pin_log_search_range: [30, 'search range of pin log(day)']
    account_activity_search_range: [24, 'search range of account_activity(hour)']
    token_life_time: [30]
    transaction_void_range: [1, 'void range of transaction(day)']
    session_life_time: [60]
    roll_shift_time: ['6,14,22', 'utc time of rolling shift(hour)']
    credit_life_time_array: ['0.5,1,3,5,7', 'array of credit life time options (day)']
    daily_deposit_limit: [25000000, 'limit amount of daily deposit (cent)']
    daily_withdraw_limit: [25000000, 'limit amount of daily withdraw (cent)']
