layout: "cage"
player_transaction:
  exception_transaction:
    casino_id: "transaction_approval.casino_id"
    player_id: "transaction_approval.player_id"
    amount: "transaction_approval.amount"
    transaction_type: "transaction_approval.transaction_type"
    payment_method: "transaction_approval.payment_method" 
    source_of_fund: "transaction_approval.source_of_fund"
player:
  merge_player:
    licensee_id: "merge_approval.licensee_id"
    player_vic_id: "merge_approval.vic_member"
    player_vic_before_amount: "merge_approval.before_amount"
    minus_amount: "merge_approval.amount"
    player_vic_after_balance: "merge_approval.after_amount"
    player_sur_id: "merge_approval.sur_member"
    player_sur_before_amount: "merge_approval.before_amount"
    amount: "merge_approval.amount"
    player_sur_after_amount: "merge_approval.after_amount"
   
