20000:
  trans_history_search_range: [30, 'search range of transaction history']
  polling_time: [1, 'interval of refreshing header']
  card_id_length: [20]
  member_id_length: [8]
  audit_log_search_range: [7, 'search range of audit log']
  change_log_search_range: [30, 'search range of player lock log']
  token_life_time: [30]
  session_life_time: [60]
  roll_shift_time: ['6,14,22', 'time of rolling shift']