development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rothorn_cms_development
  username: rothorn
  password: rothorn
  host: hq-int-cms-vdb01.laxino.local
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rothorn_cms_test
  username: rothorn
  password: rothorn
  host: hq-int-cms-vdb01.laxino.local
  port: 3306

integration0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rothorn_cms_integration
  username: rothorn
  password: rothorn
  host: hq-int-cms-vdb01.laxino.local
  port: 3306

staging0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rothorn_cms_staging
  username: rothorn
  password: rothorn
  host: mo-stg-cms-vdb01.rnd.laxino.com
  port: 3306

mockup0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rothorn_cms_mockup
  username: rothorn
  password: rothorn
  host: mo-mock-cms-vdb01.rnd.laxino.com
  port: 3306

sandbox3:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rothorn_cms_sandbox
  username: rothorn
  password: rothorn.pa$$w0rd123
  host: mo-snd-cms-vdb01.lb.laxigames.local
  port: 6034

production3:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rothorn_cms_production
  username: rothorn
  password: rothorn.pa$$w0rd123
  host: mo-prd-cms-vdb01.lb.laxigames.local
  port: 6033
