development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rothorn_cms_development
  username: rothorn
  password: rothorn
  host: mo-int-cms-vdb01.rnd.laxino.com
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rothorn_cms_test
  username: rothorn
  password: rothorn
  host: mo-int-cms-vdb01.rnd.laxino.com
  port: 3306

integration0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rothorn_cms_integration
  username: rothorn
  password: rothorn
  host: mo-int-cms-vdb01.rnd.laxino.com
  port: 3306

staging0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rothorn_cms_staging
  username: rothorn
  password: rothorn
  host: mo-stg-cms-vdb01.rnd.laxino.com
  port: 3306

