development:
  :wallet: http://mingwong01.rnd.laxino.com:5555/cwms
  :patron: http://mingwong01.rnd.laxino.com:6666
  :station: http://mingwong01.rnd.laxino.com:5000

test:
  :wallet: http://mingwong01.rnd.laxino.com:5555/cwms
  :patron: http://mingwong01.rnd.laxino.com:6666
  :station: http://mingwong01.rnd.laxino.com:5000

mockup0:
  :wallet: http://mo-mock-cwms-vapp01.rnd.laxino.com:80/cwms
  :patron: http://mo-mock-pis-vapp01.rnd.laxino.com:80
  :station: http://mo-mock-sm-vapp01.rnd.laxino.com:80
  
integration0:
  :wallet: http://hq-int-cwms-vapp01.laxino.local:80/cwms
  :patron: http://hq-int-pis-vapp01.laxino.local:80
  :station: http://hq-int-sm-vapp01.laxino.local:80

staging0:
  :wallet: http://hq-stg-cwms-vapp01.laxino.local:80/cwms
  :patron: http://hq-stg-pis-vapp01.laxino.local:80
  :station: http://hq-stg-sm-vapp01.laxino.local:80

sandbox3:
  :wallet: http://mo-snd-cwms-vapp01.lb.laxigames.local:80/cwms
  :patron: http://mo-snd-pis-vapp01.lb.laxigames.local:80
  :station: http://mo-snd-sm-vapp01.lb.laxigames.local:80

production3:
  :wallet: http://mo-prd-cwms-vapp01.lb.laxigames.local:80/cwms
  :patron: http://mo-prd-pis-vapp01.lb.laxigames.local:80
  :station: http://mo-prd-sm-vapp01.lb.laxigames.local:80
  
sandbox:
  :wallet: http://mo-snd-cwms-vapp01.platform.gamesource.local:80/cwms
  :patron: http://mo-snd-pis-vapp01.platform.gamesource.local:80
  :station: http://mo-snd-sm-vapp01.platform.gamesource.local:80
