development:
  :wallet: http://mingwong01.rnd.laxino.com:5555/cwms
  :patron: http://mingwong01.rnd.laxino.com:6666
  :station: http://marcusao01.rnd.laxino.com:5000

test:
  :wallet: http://mingwong01.rnd.laxino.com:5555/cwms
  :patron: http://mingwong01.rnd.laxino.com:6666
  :station: http://marcusao01.rnd.laxino.com:5000

mockup0:
  :wallet: http://mo-mock-cwms-vapp01.rnd.laxino.com:80/cwms
  :patron: http://mo-mock-pis-vapp01.rnd.laxino.com:80
  :station: http://mo-mock-sm-vapp01.rnd.laxino.com:80
  
integration0:
  :wallet: http://mo-int-cwms-vapp01.rnd.laxino.com:80/cwms
  :patron: http://mo-int-pis-vapp01.rnd.laxino.com:80
  :station: http://mo-int-sm-vapp01.rnd.laxino.com:80

staging0:
  :wallet: http://mo-stg-cwms-vapp01.rnd.laxino.com:80/cwms
  :patron: http://mo-stg-pis-vapp01.rnd.laxino.com:80
  :station: http://mo-stg-sm-vapp01.rnd.laxino.com:80
